modLoader="javafml"
loaderVersion=">=52"
license="MIT"

[[mods]]
modId="blackholeitemmovement"
version="1.0.0"
displayName="Black Hole"
description='''
A simple black hole mod: place receiver blocks at home and bind portable black hole items
to that receiver. Place bound black holes on chests to suck items into the receiver.
'''
authors="Doritobob"
displayURL="https://github.com/doritobob269"

[[dependencies.blackholeitemmovement]]
    modId="forge"
    mandatory=true
    versionRange="[52,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.blackholeitemmovement]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
